apiVersion: v1
kind: Namespace
metadata:
  name: my-app

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: my-app
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: my-app
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: M@tech@pp1234
            - name: MYSQL_DATABASE
              value: crud
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
        - name: init-script
          configMap:
            name: db-init-script

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: my-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
  namespace: my-app
data:
  database.sql: |
    CREATE USER app@'%' IDENTIFIED BY '1234';
    GRANT ALL PRIVILEGES ON crud.* TO app@'%';
    FLUSH PRIVILEGES;

    CREATE TABLE `students` (
      `id` int(11) NOT NULL,
      `name` varchar(255) NOT NULL,
      `email` varchar(255) NOT NULL,
      `phone` varchar(255) NOT NULL
    ) ENGINE=MyISAM DEFAULT CHARSET=latin1;

    INSERT INTO `students` (`id`, `name`, `email`, `phone`) VALUES
    (23, 'motech noel', 'mosesnoel02@gmail.com', '+255752541568'),
    (24, 'Thiago Moses', 'moses@noel.com', '0712541669'),
    (25, 'Saratex Marie', 'moses@noel.com', '0712541669'),
    (26, 'Kamonyo Kiiza', 'kamonyomoses@gmail.com', '+255752541568');

    ALTER TABLE `students`
      ADD PRIMARY KEY (`id`);

    ALTER TABLE `students`
      MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=27;
    COMMIT;

---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: my-app
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: my-app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: w3ll1n9t0n/crud_app:latest
          ports:
            - containerPort: 5000
          command:
            - sh
            - -c
            - "sleep 300 && python3 app.py"
          env:
            - name: DB_HOST
              value: db
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USERNAME
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: my-app
type: Opaque
data:
  DB_PASSWORD: MTIzNA==  # Base64-encoded value of the password
  DB_USERNAME: YXBw  # Base64-encoded value of the username
